### ISSUE TITLE
Error on Demo Start

### ISSUE THREAD

**Issue by shipswake** [finos/openfin-react-hooks#30]
I cloned the repo and followed the steps listed on the Readme

When I run Start in the Demo folder, I receive an error:

C:/Code/samples/Openfin/openfin-react-hooks/demo/src/App.tsx
TypeScript error in C:/Code/samples/Openfin/openfin-react-hooks/demo/src/App.tsx(76,27):
Expected 2 type arguments, but got 1.  TS2558

    74 | };
    75 | 
  > 76 | export default withRouter<RouteComponentProps>(App);
       |                           ^
    77 |

**Comment by oriondean** [comment]
Hi @shipswake , thanks for reporting this.

Do you happen to know what version of `@types/react-router` you have installed?

**Comment by oriondean** [comment]
What output do you get if you run `npm ls @types/react-router-dom`? 
I suspect that for some reason `@types/react-router-dom v5.1.3` has been installed when the `package-lock.json` stipulates that `v.5.0.0` should be installed. 
Did you happen to ignore the package-lock in any way when running `npm install` within the `demo` directory? If not, might be safer just to explicitly add `@types/react-router` as a dependency here
